export default {
  translation: {
    signIn: 'Вход',
    signUp: 'Регистрация',
    userNike: 'Ваш ник',
    userName: 'Имя пользователя',
    password: 'Пароль',
    passwordConfirmation: 'Подтвердите пароль',
    notAccount: 'Нет аккаунта?',
    errors: {
      required: 'Обязательное поле',
      logIn: 'Неверные имя пользователя или пароль',
      userNameLength: 'От 3 до 20 символов',
      userNameExists: 'Такой пользователь уже существует',
      password: 'Не менее 6 символов',
      passwordConfirmation: 'Пароли должны совпадать',
      unique: 'Должно быть уникальным',
    },
    notFound: {
      pageNotFound: 'Страница не найдена',
      mayRedirect: 'Но вы можете перейти на ',
      mainPage: 'главную страницу',
    },
    chat: {
      send: 'Отправить',
      channels: 'Каналы',
      message_one: '{{count}} сообщение',
      message_few: '{{count}} сообщения',
      message_many: '{{count}} сообщений',
      remove: 'Удалить',
      rename: 'Переименовать',
      newMessage: 'Новое сообщение',
      typeNewMessage: 'Введите сообщение...',
      addChannel: 'Добавить канал',
      removeChannel: 'Удалить канал',
      renameChannel: 'Переименовать канал',
      areYouSure: 'Уверены?',
      channelName: 'Имя канала',
    },
    buttons: {
      cancel: 'Отменить',
      send: 'Отправить',
      remove: 'Удалить',
      logOut: 'Выйти',
      logIn: 'Войти',
      singUp: 'Зарегистрироваться',
      channelManage: 'Управление каналом',
    },
    messages: {
      addChannel: 'Канал создан',
      renameChannel: 'Канал переименован',
      removeChannel: 'Канал удалён',
      connectionError: 'Ошибка соединения',
    },
  },
};
